// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaccinationSystem.Infrastructure.Data;

#nullable disable

namespace VaccinationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909083127_SeedInventoryData")]
    partial class SeedInventoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VaccinationSystem.Core.Entities.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("integer");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("VaccineId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BatchNumber = "PF-2024-001",
                            CreatedAt = new DateTime(2026, 9, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6124),
                            ExpiryDate = new DateTime(2027, 3, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6110),
                            QuantityAvailable = 100,
                            QuantityReceived = 100,
                            StorageLocation = "Fridge A1",
                            Supplier = "Pfizer Inc.",
                            VaccineId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BatchNumber = "MOD-2024-002",
                            CreatedAt = new DateTime(2026, 9, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6137),
                            ExpiryDate = new DateTime(2027, 5, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6132),
                            QuantityAvailable = 145,
                            QuantityReceived = 150,
                            StorageLocation = "Fridge B2",
                            Supplier = "Moderna Therapeutics",
                            VaccineId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BatchNumber = "AZ-2024-003",
                            CreatedAt = new DateTime(2026, 9, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6166),
                            ExpiryDate = new DateTime(2026, 10, 24, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6160),
                            QuantityAvailable = 200,
                            QuantityReceived = 200,
                            StorageLocation = "Room C3",
                            Supplier = "AstraZeneca UK",
                            VaccineId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("VaccinationSystem.Core.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("TransactionDate");

                    b.ToTable("InventoryTransactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BatchId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 8, 30, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6214),
                            Quantity = 100,
                            Reason = "Initial stock receipt",
                            TransactionDate = new DateTime(2026, 8, 30, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6212),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BatchId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 9, 1, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6228),
                            Quantity = 150,
                            Reason = "Initial stock receipt",
                            TransactionDate = new DateTime(2026, 9, 1, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6226),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            BatchId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 9, 6, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6239),
                            Quantity = 5,
                            Reason = "Issued to Vaccination Session #101",
                            TransactionDate = new DateTime(2026, 9, 6, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6238),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BatchId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 9, 4, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6250),
                            Quantity = 200,
                            Reason = "Initial stock receipt",
                            TransactionDate = new DateTime(2026, 9, 4, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(6248),
                            Type = 0
                        });
                });

            modelBuilder.Entity("VaccinationSystem.Core.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(5830),
                            Dosage = "0.3ml",
                            Manufacturer = "Pfizer",
                            Name = "Pfizer-BioNTech",
                            Type = "mRNA"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 9, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(5839),
                            Dosage = "0.5ml",
                            Manufacturer = "Moderna",
                            Name = "Moderna",
                            Type = "mRNA"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 9, 9, 8, 31, 26, 980, DateTimeKind.Utc).AddTicks(5846),
                            Dosage = "0.5ml",
                            Manufacturer = "AstraZeneca",
                            Name = "AstraZeneca",
                            Type = "Viral Vector"
                        });
                });

            modelBuilder.Entity("VaccinationSystem.Core.Entities.Batch", b =>
                {
                    b.HasOne("VaccinationSystem.Core.Entities.Vaccine", "Vaccine")
                        .WithMany("Batches")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccinationSystem.Core.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("VaccinationSystem.Core.Entities.Batch", "Batch")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("VaccinationSystem.Core.Entities.Batch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VaccinationSystem.Core.Entities.Vaccine", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
